In [12]:
import numpy as np

class KalmanFilter2D:
    def __init__(self):
        # State vector [x, y, vx, vy] (position and velocity)
        self.state = np.array([[0.0], [0.0], [0.0], [0.0]], dtype=float)  # Float values
        self.P = np.eye(4, dtype=float)  # Initial covariance matrix
        self.A = np.array([[1, 0, 1, 0],
                           [0, 1, 0, 1],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=float)  # State transition matrix
        self.H = np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0]], dtype=float)  # Measurement matrix
        self.R = np.eye(2, dtype=float)  # Measurement noise
        self.Q = np.eye(4, dtype=float) * 0.1  # Process noise

    def predict(self):
        self.state = np.dot(self.A, self.state)
        self.P = np.dot(self.A, np.dot(self.P, self.A.T)) + self.Q
        return self.state[:2]

    def update(self, measurement):
        y = measurement - np.dot(self.H, self.state)
        S = np.dot(self.H, np.dot(self.P, self.H.T)) + self.R
        K = np.dot(self.P, np.dot(self.H.T, np.linalg.inv(S)))
        self.state += np.dot(K, y)
        self.P = self.P - np.dot(K, np.dot(self.H, self.P))
        return self.state[:2]

# Test the Kalman Filter
kf = KalmanFilter2D()
measurements = [np.array([[1.0], [1.0]]), np.array([[2.0], [2.0]]), np.array([[3.0], [3.0]])]

for measurement in measurements:
    predicted = kf.predict()
    updated = kf.update(measurement)
    print(f"Predicted: {predicted.flatten()}, Updated: {updated.flatten()}")


Predicted: [0.67741935 0.67741935], Updated: [0.67741935 0.67741935]
Predicted: [1.6875 1.6875], Updated: [1.6875 1.6875]
Predicted: [2.78274869 2.78274869], Updated: [2.78274869 2.78274869]


In [7]:
#2
import numpy as np

def normalize_image(image):
    """
    Normalize an image array to have pixel values between 0 and 1.
    """
    return image / 255.0

# Example usage
image = np.random.randint(0, 256, (5, 5, 3))  # Dummy image
normalized_image = normalize_image(image)
print("Normalized Image:\n", normalized_image)


Normalized Image:
 [[[0.22745098 0.31764706 0.60392157]
  [0.49803922 0.50980392 0.56862745]
  [0.63137255 0.79215686 0.86666667]
  [0.4        0.33333333 0.47843137]
  [0.49803922 0.0627451  0.21568627]]

 [[0.90196078 0.34901961 0.23529412]
  [0.49019608 0.8627451  0.52156863]
  [0.61568627 0.51372549 0.14509804]
  [0.00784314 0.46666667 0.50588235]
  [0.69411765 0.90196078 0.07058824]]

 [[0.41960784 0.28235294 0.54509804]
  [0.4745098  0.49803922 0.06666667]
  [0.43921569 0.87843137 0.61176471]
  [0.13333333 0.69019608 0.02745098]
  [0.28627451 0.11764706 0.23137255]]

 [[0.53333333 0.8        0.25490196]
  [0.37254902 0.94117647 0.63921569]
  [0.56862745 0.90980392 0.87058824]
  [0.79215686 0.01960784 0.6627451 ]
  [0.40784314 0.68627451 0.90196078]]

 [[0.1372549  0.91372549 0.55686275]
  [0.15294118 0.69803922 0.61568627]
  [0.23137255 0.76470588 0.94509804]
  [0.16470588 0.04313725 0.30588235]
  [0.09019608 0.2627451  0.28627451]]]


In [3]:
#3
import numpy as np

def generate_dummy_detections(num_detections=5):
    """
    Generate dummy object detection data with confidence scores and bounding boxes.
    """
    detections = []
    for _ in range(num_detections):
        confidence = np.random.rand()
        bbox = np.random.randint(0, 100, 4)  # [x_min, y_min, x_max, y_max]
        detections.append((confidence, bbox))
    return detections

def filter_detections(detections, threshold=0.5):
    """
    Filter detections by confidence threshold.
    """
    return [d for d in detections if d[0] >= threshold]

# Example
detections = generate_dummy_detections()
filtered_detections = filter_detections(detections)
print("Filtered Detections:", filtered_detections)


Filtered Detections: [(0.7272903044631136, array([88, 46, 11, 25]))]


In [2]:
# Restart the kernel
get_ipython().kernel.do_shutdown(restart=True)

{'status': 'ok', 'restart': True}

In [4]:
#4
def extract_feature_vectors(detections):
    """
    Extract random 128-dimensional feature vectors for each detection.
    """
    feature_vectors = [np.random.rand(128) for _ in detections]
    return feature_vectors

# Example
features = extract_feature_vectors(detections)
print("Feature Vectors Shape:", np.array(features).shape)


Feature Vectors Shape: (5, 128)


In [5]:
from scipy.spatial.distance import euclidean

def reidentify_objects(features1, features2):
    """
    Match feature vectors based on Euclidean distance.
    """
    matches = []
    for i, f1 in enumerate(features1):
        best_match = min(features2, key=lambda f2: euclidean(f1, f2))
        matches.append((i, best_match))
    return matches

# Example
matches = reidentify_objects(features, features)
print("Re-Identification Matches:", matches)


Re-Identification Matches: [(0, array([8.17944786e-01, 3.42024859e-01, 3.47853448e-01, 2.01579957e-01,
       2.04594452e-01, 2.20826882e-01, 4.46142729e-01, 6.29220683e-01,
       3.71426818e-01, 3.15435842e-02, 8.21494660e-01, 7.91236064e-01,
       7.17238551e-01, 5.87325841e-01, 5.82886855e-01, 6.83233283e-01,
       2.20808100e-01, 1.83774415e-01, 4.41337061e-01, 1.59964693e-01,
       6.53953428e-01, 3.20266169e-01, 4.55231709e-01, 2.73097828e-01,
       4.30954165e-01, 3.22069582e-01, 1.66595046e-01, 1.49702982e-01,
       4.23600314e-01, 1.85009120e-01, 7.69152640e-01, 4.23141547e-01,
       4.36391833e-01, 8.18392671e-01, 1.64607091e-01, 8.08221646e-01,
       8.28807347e-01, 2.52989599e-01, 8.94519240e-02, 5.29587289e-01,
       9.56061895e-01, 8.04876798e-01, 6.86820359e-01, 4.45161453e-01,
       8.73119049e-03, 2.82943709e-02, 5.98510823e-01, 2.74580832e-01,
       2.39034525e-01, 9.99383760e-01, 9.65344832e-01, 4.28991168e-01,
       8.83142700e-01, 7.27268108e-01, 6.5820

In [13]:
# Theory

In [14]:
# 1.
# Detectron2 tasks: It supports object detection, instance segmentation, keypoint detection, and panoptic segmentation.

In [14]:
#2 - 35
# Data annotation importance: Proper labeling helps models learn features accurately, improving prediction performance.
# Batch size: The number of samples processed together in one forward/backward pass during training.
# Pretrained weights purpose: They provide a starting point for models, speeding up convergence and improving accuracy.
# Verify Detectron2 installation: Run import detectron2; print(detectron2.__version__) in Python.
# TFOD2: TensorFlow Object Detection API, widely used for training custom object detection models.
# Learning rate: Controls how much the model's weights are updated during training; too high can cause instability.
# Detectron2 backend: It uses PyTorch for its flexibility, efficiency, and dynamic computational graph.
# Pretrained models in TFOD2: Supports SSD, Faster R-CNN, and EfficientDet models.
# Data path errors in Detectron2: They prevent proper loading of datasets or models, causing training failures.
# Detectron2: A powerful PyTorch-based library for object detection and segmentation.
# TFRecord files: Efficient format for storing large datasets in TensorFlow.
# Evaluation metrics in Detectron2: Common ones are mAP (mean Average Precision) and IoU (Intersection over Union).
# Inference with Detectron2: Load a trained model and use predictor(image) to get predictions.
# TFOD2 meaning: TensorFlow Object Detection API, designed for building and deploying object detection models.
# Fine-tuning: Adjusting a pretrained model to improve its performance on a specific task.
# Starting training in TFOD2: Run the training script using TensorFlow's model_main_tf2.py.
# COCO format: A widely-used data format for object detection with JSON files describing annotations.
# Evaluation curve plotting: Helps visualize training progress and model performance.
# Configuring data paths in TFOD2: Update pipeline.config to point to datasets and label maps.
# Detectron2 on CPU: Yes, but it’s slower compared to using a GPU.
# Label maps in TFOD2: Define the class labels for detection tasks.
# TFOD2 for real-time tasks: Supports efficient models like SSD and EfficientDet for faster inference.
# Batch size impact on GPU memory: Larger batches require more memory; small batches can lead to noisier gradients.
# Role of IoU: Measures overlap between predicted and ground truth bounding boxes; key for evaluating detection accuracy.
# Faster R-CNN: A two-stage object detection model supported by TFOD2; it balances speed and accuracy.
# Detectron2 pretrained weights: They help models generalize better by leveraging pre-learned features.
# Training data format in TFOD2: Typically stored in TFRecord files for efficient reading during training.
# Semantic vs. Instance Segmentation: Semantic labels each pixel with a class; instance segmentation distinguishes individual objects.
# Custom classes in Detectron2: Yes, by training the model on your custom-labeled dataset.
# Importance of pipeline.config: Defines all training parameters, including model architecture and data paths.
# Models supported by TFOD2: SSD, Faster R-CNN, EfficientDet, and CenterNet, among others.
# Learning rate too high: Causes unstable training and prevents the model from converging.
# COCO JSON format: A JSON structure defining image data, categories, and annotations in the COCO dataset format.
# TensorFlow Lite compatibility: Enables deployment of lightweight models for mobile and edge devices.
# Let me know if you need more details on any!










